const initialWordList = [
    { id: 1, italian: 'il', polish: 'rodzajnik męski', example_it: 'Il cane è grande.', example_pl: 'Pies jest duży.' },
    { id: 2, italian: 'la', polish: 'rodzajnik żeński', example_it: 'La casa è bella.', example_pl: 'Dom jest ładny.' },
    { id: 3, italian: 'un', polish: 'rodzajnik nieokreślony męski', example_it: 'Ho un libro.', example_pl: 'Mam książkę.' },
    { id: 4, italian: 'una', polish: 'rodzajnik nieokreślony żeński', example_it: 'È una sedia.', example_pl: 'To jest krzesło.' },
    { id: 5, italian: 'io', polish: 'ja', example_it: 'Io sono felice.', example_pl: 'Jestem szczęśliwy.' },
    { id: 6, italian: 'tu', polish: 'ty', example_it: 'Tu parli italiano.', example_pl: 'Ty mówisz po włosku.' },
    { id: 7, italian: 'lui', polish: 'on', example_it: 'Lui è mio amico.', example_pl: 'On jest moim przyjacielem.' },
    { id: 8, italian: 'lei', polish: 'ona', example_it: 'Lei è mia sorella.', example_pl: 'Ona jest moją siostrą.' },
    { id: 9, italian: 'noi', polish: 'my', example_it: 'Noi andiamo a scuola.', example_pl: 'My idziemy do szkoły.' },
    { id: 10, italian: 'voi', polish: 'wy', example_it: 'Voi siete bravi.', example_pl: 'Wy jesteście dobrzy.' },
    { id: 11, italian: 'loro', polish: 'oni', example_it: 'Loro vivono qui.', example_pl: 'Oni mieszkają tutaj.' },
    { id: 12, italian: 'essere', polish: 'być', example_it: 'Voglio essere felice.', example_pl: 'Chcę być szczęśliwy.' },
    { id: 13, italian: 'avere', polish: 'mieć', example_it: 'Ho due gatti.', example_pl: 'Mam dwa koty.' },
    { id: 14, italian: 'fare', polish: 'robić', example_it: 'Cosa vuoi fare?', example_pl: 'Co chcesz robić?' },
    { id: 15, italian: 'andare', polish: 'iść, jechać', example_it: 'Domani andiamo al mare.', example_pl: 'Jutro jedziemy nad morze.' },
    { id: 16, italian: 'venire', polish: 'przyjść', example_it: 'Vuoi venire con me?', example_pl: 'Chcesz iść ze mną?' },
    { id: 17, italian: 'dire', polish: 'mówić, powiedzieć', example_it: 'Cosa vuoi dire?', example_pl: 'Co chcesz powiedzieć?' },
    { id: 18, italian: 'parlare', polish: 'rozmawiać', example_it: 'Parlo inglese.', example_pl: 'Mówię po angielsku.' },
    { id: 19, italian: 'vedere', polish: 'widzieć', example_it: 'Non vedo niente.', example_pl: 'Nic nie widzę.' },
    { id: 20, italian: 'dare', polish: 'dać', example_it: 'Mi puoi dare una mano?', example_pl: 'Możesz mi pomóc?' },
    { id: 21, italian: 'prendere', polish: 'brać', example_it: 'Prendo un caffè.', example_pl: 'Wezmę kawę.' },
    { id: 22, italian: 'mangiare', polish: 'jeść', example_it: 'Mangio la pizza.', example_pl: 'Jem pizzę.' },
    { id: 23, italian: 'bere', polish: 'pić', example_it: 'Bevo acqua.', example_pl: 'Piję wodę.' },
    { id: 24, italian: 'vivere', polish: 'żyć, mieszkać', example_it: 'Vivo a Roma.', example_pl: 'Mieszkam w Rzymie.' },
    { id: 25, italian: 'sapere', polish: 'wiedzieć, umieć', example_it: 'So parlare italiano.', example_pl: 'Umiem mówić po włosku.' },
    { id: 26, italian: 'potere', polish: 'móc', example_it: 'Posso entrare?', example_pl: 'Mogę wejść?' },
    { id: 27, italian: 'volere', polish: 'chcieć', example_it: 'Voglio dormire.', example_pl: 'Chcę spać.' },
    { id: 28, italian: 'dovere', polish: 'musieć', example_it: 'Devo lavorare.', example_pl: 'Muszę pracować.' },
    { id: 29, italian: 'amare', polish: 'kochać', example_it: 'Ti amo.', example_pl: 'Kocham cię.' },
    { id: 30, italian: 'piacere', polish: 'lubić', example_it: 'Mi piace la musica.', example_pl: 'Lubię muzykę.' },
    { id: 31, italian: 'grande', polish: 'duży', example_it: 'Il tavolo è grande.', example_pl: 'Stół jest duży.' },
    { id: 32, italian: 'piccolo', polish: 'mały', example_it: 'La stanza è piccola.', example_pl: 'Pokój jest mały.' },
    { id: 33, italian: 'buono', polish: 'dobry', example_it: 'Questo vino è buono.', example_pl: 'To wino jest dobre.' },
    { id: 34, italian: 'cattivo', polish: 'zły', example_it: 'Ha avuto una cattiva giornata.', example_pl: 'Miał zły dzień.' },
    { id: 35, italian: 'bello', polish: 'piękny', example_it: 'Che bello film!', example_pl: 'Jaki piękny film!' },
    { id: 36, italian: 'nuovo', polish: 'nowy', example_it: 'Ho un telefono nuovo.', example_pl: 'Mam nowy telefon.' },
    { id: 37, italian: 'vecchio', polish: 'stary', example_it: 'È un libro vecchio.', example_pl: 'To stara książka.' },
    { id: 38, italian: 'giorno', polish: 'dzień', example_it: 'Buongiorno!', example_pl: 'Dzień dobry!' },
    { id: 39, italian: 'notte', polish: 'noc', example_it: 'Buonanotte!', example_pl: 'Dobranoc!' },
    { id: 40, italian: 'uomo', polish: 'mężczyzna', example_it: 'Lui è un uomo gentile.', example_pl: 'On jest miłym mężczyzną.' },
    { id: 41, italian: 'donna', polish: 'kobieta', example_it: 'Lei è una donna forte.', example_pl: 'Ona jest silną kobietą.' },
    { id: 42, italian: 'bambino', polish: 'dziecko (chłopiec)', example_it: 'Il bambino gioca.', example_pl: 'Chłopiec się bawi.' },
    { id: 43, italian: 'bambina', polish: 'dziecko (dziewczynka)', example_it: 'La bambina canta.', example_pl: 'Dziewczynka śpiewa.' },
    { id: 44, italian: 'amico', polish: 'przyjaciel', example_it: 'Ho un amico italiano.', example_pl: 'Mam włoskiego przyjaciela.' },
    { id: 45, italian: 'amica', polish: 'przyjaciółka', example_it: 'Lei è la mia amica.', example_pl: 'Ona jest moją przyjaciółką.' },
    { id: 46, italian: 'madre', polish: 'matka', example_it: 'Mia madre cucina bene.', example_pl: 'Moja mama dobrze gotuje.' },
    { id: 47, italian: 'padre', polish: 'ojciec', example_it: 'Mio padre lavora molto.', example_pl: 'Mój tata dużo pracuje.' },
    { id: 48, italian: 'fratello', polish: 'brat', example_it: 'Ho un fratello maggiore.', example_pl: 'Mam starszego brata.' },
    { id: 49, italian: 'sorella', polish: 'siostra', example_it: 'La mia sorella è simpatica.', example_pl: 'Moja siostra jest sympatyczna.' },
    { id: 50, italian: 'casa', polish: 'dom', example_it: 'La casa è grande.', example_pl: 'Dom jest duży.' },
    { id: 51, italian: 'scuola', polish: 'szkoła', example_it: 'La scuola è vicina.', example_pl: 'Szkoła jest blisko.' },
    { id: 52, italian: 'lavoro', polish: 'praca', example_it: 'Ho molto lavoro.', example_pl: 'Mam dużo pracy.' },
    { id: 53, italian: 'strada', polish: 'ulica', example_it: 'La strada è lunga.', example_pl: 'Ulica jest długa.' },
    { id: 54, italian: 'città', polish: 'miasto', example_it: 'Roma è una città bella.', example_pl: 'Rzym to piękne miasto.' },
    { id: 55, italian: 'paese', polish: 'kraj, miasteczko', example_it: 'L’Italia è un bel paese.', example_pl: 'Włochy to piękny kraj.' },
    { id: 56, italian: 'tempo', polish: 'czas, pogoda', example_it: 'Non ho tempo.', example_pl: 'Nie mam czasu.' },
    { id: 57, italian: 'anno', polish: 'rok', example_it: 'Quest’anno viaggio molto.', example_pl: 'W tym roku dużo podróżuję.' },
    { id: 58, italian: 'mese', polish: 'miesiąc', example_it: 'È il mese di maggio.', example_pl: 'To miesiąc maj.' },
    { id: 59, italian: 'settimana', polish: 'tydzień', example_it: 'La settimana è lunga.', example_pl: 'Tydzień jest długi.' },
    { id: 60, italian: 'oggi', polish: 'dzisiaj', example_it: 'Oggi è una bella giornata.', example_pl: 'Dziś jest ładny dzień.' },
    { id: 61, italian: 'ieri', polish: 'wczoraj', example_it: 'Ieri ho studiato molto.', example_pl: 'Wczoraj dużo się uczyłem.' },
    { id: 62, italian: 'domani', polish: 'jutro', example_it: 'Domani andiamo al mare.', example_pl: 'Jutro jedziemy nad morze.' },
    { id: 63, italian: 'ora', polish: 'godzina, teraz', example_it: 'Che ora è?', example_pl: 'Która jest godzina?' },
    { id: 64, italian: 'sempre', polish: 'zawsze', example_it: 'Sono sempre felice.', example_pl: 'Zawsze jestem szczęśliwy.' },
    { id: 65, italian: 'mai', polish: 'nigdy', example_it: 'Non dico mai bugie.', example_pl: 'Nigdy nie kłamię.' },
    { id: 66, italian: 'spesso', polish: 'często', example_it: 'Vado spesso al cinema.', example_pl: 'Często chodzę do kina.' },
    { id: 67, italian: 'adesso', polish: 'teraz', example_it: 'Devo andare adesso.', example_pl: 'Muszę iść teraz.' },
    { id: 68, italian: 'qui', polish: 'tutaj', example_it: 'Vivo qui.', example_pl: 'Mieszkam tutaj.' },
    { id: 69, italian: 'lì', polish: 'tam', example_it: 'La mia borsa è lì.', example_pl: 'Moja torba jest tam.' },
    { id: 70, italian: 'molto', polish: 'dużo, bardzo', example_it: 'Ho molto lavoro.', example_pl: 'Mam dużo pracy.' },
    { id: 71, italian: 'poco', polish: 'mało, trochę', example_it: 'Ho poco tempo.', example_pl: 'Mam mało czasu.' },
    { id: 72, italian: 'bene', polish: 'dobrze', example_it: 'Sto bene.', example_pl: 'Czuję się dobrze.' },
    { id: 73, italian: 'male', polish: 'źle', example_it: 'Mi sento male.', example_pl: 'Źle się czuję.' },
    { id: 74, italian: 'vicino', polish: 'blisko', example_it: 'La farmacia è qui vicino.', example_pl: 'Apteka jest blisko.' },
    { id: 75, italian: 'lontano', polish: 'daleko', example_it: 'Il mare è lontano.', example_pl: 'Morze jest daleko.' },
    { id: 76, italian: 'grigio', polish: 'szary', example_it: 'Il cielo è grigio.', example_pl: 'Niebo jest szare.' },
    { id: 77, italian: 'rosso', polish: 'czerwony', example_it: 'La mela è rossa.', example_pl: 'Jabłko jest czerwone.' },
    { id: 78, italian: 'blu', polish: 'niebieski', example_it: 'Il mare è blu.', example_pl: 'Morze jest niebieskie.' },
    { id: 79, italian: 'verde', polish: 'zielony', example_it: 'L’erba è verde.', example_pl: 'Trawa jest zielona.' },
    { id: 80, italian: 'giallo', polish: 'żółty', example_it: 'Il sole è giallo.', example_pl: 'Słońce jest żółte.' },
    { id: 81, italian: 'bianco', polish: 'biały', example_it: 'La neve è bianca.', example_pl: 'Śnieg jest biały.' },
    { id: 82, italian: 'nero', polish: 'czarny', example_it: 'Il gatto è nero.', example_pl: 'Kot jest czarny.' },
    { id: 83, italian: 'caldo', polish: 'ciepły, gorący', example_it: 'Il caffè è caldo.', example_pl: 'Kawa jest gorąca.' },
    { id: 84, italian: 'freddo', polish: 'zimny', example_it: 'L’acqua è fredda.', example_pl: 'Woda jest zimna.' },
    { id: 85, italian: 'alto', polish: 'wysoki', example_it: 'Lui è molto alto.', example_pl: 'On jest bardzo wysoki.' },
    { id: 86, italian: 'basso', polish: 'niski', example_it: 'Il tavolo è basso.', example_pl: 'Stół jest niski.' },
    { id: 87, italian: 'lungo', polish: 'długi', example_it: 'La strada è lunga.', example_pl: 'Ulica jest długa.' },
    { id: 88, italian: 'corto', polish: 'krótki', example_it: 'La lezione è corta.', example_pl: 'Lekcja jest krótka.' },
    { id: 89, italian: 'veloce', polish: 'szybki', example_it: 'La macchina è veloce.', example_pl: 'Samochód jest szybki.' },
    { id: 90, italian: 'lento', polish: 'wolny', example_it: 'Il treno è lento.', example_pl: 'Pociąg jest wolny.' },
    { id: 91, italian: 'giorno', polish: 'dzień', example_it: 'Il giorno è soleggiato.', example_pl: 'Dzień jest słoneczny.' },
    { id: 92, italian: 'sera', polish: 'wieczór', example_it: 'Buona sera!', example_pl: 'Dobry wieczór!' },
    { id: 93, italian: 'mattina', polish: 'rano', example_it: 'La mattina bevo caffè.', example_pl: 'Rano piję kawę.' },
    { id: 94, italian: 'mezzogiorno', polish: 'południe', example_it: 'È mezzogiorno.', example_pl: 'Jest południe.' },
    { id: 95, italian: 'mezzanotte', polish: 'północ', example_it: 'È mezzanotte.', example_pl: 'Jest północ.' },
    { id: 96, italian: 'pomeriggio', polish: 'popołudnie', example_it: 'Oggi pomeriggio studio.', example_pl: 'Dziś po południu się uczę.' },
    { id: 97, italian: 'famiglia', polish: 'rodzina', example_it: 'Ho una grande famiglia.', example_pl: 'Mam dużą rodzinę.' },
    { id: 98, italian: 'amore', polish: 'miłość', example_it: 'L’amore è importante.', example_pl: 'Miłość jest ważna.' },
    { id: 99, italian: 'amicizia', polish: 'przyjaźń', example_it: 'La nostra amicizia è forte.', example_pl: 'Nasza przyjaźń jest silna.' },
    { id: 100, italian: 'pace', polish: 'pokój', example_it: 'Vogliamo la pace.', example_pl: 'Chcemy pokoju.' }
];

